name: build
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json', './package.json') }}
        id: cache

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --prefer-offline

      - name: Build
        run: npm run build
