name: release-please
on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
